# Generated by Django 3.0.5 on 2020-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200630_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='account.CategoryProfile'),
        ),
    ]
