# Generated by Django 3.0.5 on 2020-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200409_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_pr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
