# Generated by Django 3.0.5 on 2020-07-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200701_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_type',
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pice_type', to='shop.PriceType'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_pr',
        ),
        migrations.AddField(
            model_name='product',
            name='type_pr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_pr', to='shop.TypePr'),
        ),
    ]
