# Generated by Django 3.0.5 on 2020-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200702_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_product',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='image_dop1',
            field=models.ImageField(blank=True, upload_to='products/image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_dop2',
            field=models.ImageField(blank=True, upload_to='products/image/%Y/%m/%d'),
        ),
    ]
