# Generated by Django 3.0.5 on 2020-08-11 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_auto_20200808_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='product_buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
