# Generated by Django 3.0.5 on 2020-08-11 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200811_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_order',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
