# Generated by Django 3.0.5 on 2020-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200811_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='comment_image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_dop1',
            field=models.ImageField(blank=True, upload_to='comment_image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image_dop2',
            field=models.ImageField(blank=True, upload_to='comment_image'),
        ),
    ]
