# Generated by Django 3.0.5 on 2020-08-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200825_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='image0',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='image_dop1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='image_dop2',
            new_name='image2',
        ),
        migrations.AlterField(
            model_name='product',
            name='file_product',
            field=models.FileField(blank=True, upload_to='products/file'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_dop1',
            field=models.ImageField(blank=True, upload_to='products/image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_dop2',
            field=models.ImageField(blank=True, upload_to='products/image'),
        ),
    ]
