# Generated by Django 3.0.5 on 2020-07-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_auto_20200705_1051'),
        ('blog', '0006_post_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_auto_20200705_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMinors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(blank=True, related_name='category_minors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Proect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='proects/image/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('timetable', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('announcement', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='chats.Chat')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_proect', to='chats.Chat')),
                ('curator', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator', to=settings.AUTH_USER_MODEL)),
                ('major', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major', to=settings.AUTH_USER_MODEL)),
                ('minors', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='minors', to='proect.Minor')),
                ('post', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('product', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement')),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
