# Generated by Django 3.0.5 on 2020-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proect',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proect',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
