# Generated by Django 3.0.5 on 2020-07-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0003_auto_20200710_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proect',
            name='minors',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minors', to='proect.Minor'),
        ),
    ]
