# Generated by Django 3.0.5 on 2020-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proect', '0004_auto_20200710_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minor',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_minors', to='proect.CategoryMinors'),
        ),
    ]
