# Generated by Django 3.0.5 on 2020-07-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_bookmark'),
        ('announcement', '0002_auto_20200705_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proect', '0005_auto_20200710_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proect',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proect',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='proect',
            name='minors',
        ),
        migrations.AddField(
            model_name='proect',
            name='minors',
            field=models.ManyToManyField(blank=True, null=True, related_name='minors', to='proect.Minor'),
        ),
        migrations.AlterField(
            model_name='proect',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='proect',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.Announcement'),
        ),
    ]
