# Generated by Django 3.0.5 on 2020-07-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('name',)},
        ),
    ]
