# Generated by Django 3.0.5 on 2020-08-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartuser_get_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='get_total_price',
        ),
    ]
