# Generated by Django 3.0.5 on 2020-06-30 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saler', to=settings.AUTH_USER_MODEL),
        ),
    ]
